

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -F anything
  yagna:
    build:
      context: ./yagna
      dockerfile: Dockerfile
      args:
        - YAGNA_VERSION=pre-rel-v0.15.0-rc31
    command: yagna service run
    environment:
      - YAGNA_AUTOCONF_APPKEY=66667777888
      - YAGNA_AUTOCONF_ID_SECRET=0000000000000000000000000000000000000000000000000000000222222222
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/