

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -F anything
    environment:
      - YAGNA_APPKEY_=66667777888
      - YAGNA_APPKEY=66667777888
      - YAGNA_API_KEY=66667777888
      - YAGNA_API_URL=http://yagna:7465
      - JWT_SECRET=dup]a
      - JWT_TOKEN_EXPIRATION=1d
      - JWT_REFRESH_TOKEN_EXPIRATION=7d
      - JWT_ISSUER=golem.network
      - MONGO_URI=mongodb://root:example@mongo:27017/
      - PORT=5174
      - DB_NAME="depositDB"

  yagna:
    build:
      context: ./yagna
      dockerfile: Dockerfile
      args:
        - YAGNA_VERSION=pre-rel-v0.15.0-rc31
    command: yagna service run
    environment:
      - YAGNA_AUTOCONF_APPKEY=66667777888
      - YAGNA_AUTOCONF_ID_SECRET=0000000000000000000000000000000000000000000000000000000222222222
      - YAGNA_API_URL=http://0.0.0.0:7465
      - SUBNET=change_me
      - YA_NET_BIND_URL=udp://0.0.0.0:0
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/