services:
  # application service
  backend:
    build:
      context: ./yagna
      dockerfile: Dockerfile
      args:
        - YAGNA_VERSION=pre-rel-v0.15.0-deposits-beta3
    command: pnpm run start
    working_dir: /app/backend
    environment:
      - YAGNA_APPKEY=${YAGNA_APPKEY}
      - YAGNA_API_URL=http://yagna:7465
      - JWT_SECRET=dup]a
      - JWT_TOKEN_EXPIRATION=1d
      - JWT_REFRESH_TOKEN_EXPIRATION=7d
      - JWT_ISSUER=golem.network
      - MONGO_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/
      - HOST=0.0.0.0
      - PORT=5174
      - DB_NAME=depositDB
      - DEPOSIT_CONTRACT_ADDRESS=0xA3D86ebF4FAC94114526f4D09C3fA093898347a6
    ports:
      - "5174:5174"
    depends_on:
      - yagna
      - mongo
    volumes:
      - ../:/app

  frontend:
    build:
      context: ./yagna
      dockerfile: Dockerfile
      args:
        - YAGNA_VERSION=pre-rel-v0.15.0-deposits-beta3
    command: pnpm run start
    working_dir: /app/frontend
    environment:
      - YAGNA_APPKEY=${YAGNA_APPKEY}
      - YAGNA_API_URL=http://yagna:7465
      - JWT_SECRET=dup]a
      - JWT_TOKEN_EXPIRATION=1d
      - JWT_REFRESH_TOKEN_EXPIRATION=7d
      - JWT_ISSUER=golem.network
      - MONGO_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/
      - HOST=0.0.0.0
      - PORT=5174
      - DB_NAME=depositDB
      - DEPOSIT_CONTRACT_ADDRESS=0xA3D86ebF4FAC94114526f4D09C3fA093898347a6

    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ../:/app
  # yagna service
  yagna:
    build:
      context: ./yagna
      dockerfile: Dockerfile
      args:
        - YAGNA_VERSION=pre-rel-v0.15.0-deposits-beta3
    command: yagna service run
    environment:
      - YAGNA_AUTOCONF_APPKEY=${YAGNA_APPKEY}
      - YAGNA_AUTOCONF_ID_SECRET=${YAGNA_PRIVATE_KEY}
      - YAGNA_API_URL=http://0.0.0.0:7465
      - SUBNET=${SUBNET}
      - YA_NET_BIND_URL=udp://0.0.0.0:0
  # mongo service
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=project
    ports:
      - "27017:27017"

  # mongo express service
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
      - mongo
    ports:
      - "8888:8081"
