services:
  # application service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app/backend
    environment:
      - YAGNA_APPKEY=${YAGNA_APPKEY}
      - YAGNA_API_URL=http://yagna:7465
      - GSB_URL=tcp://yagna:7464
      - JWT_SECRET=dupa
      - JWT_TOKEN_EXPIRATION=1d
      - JWT_REFRESH_TOKEN_EXPIRATION=7d
      - JWT_ISSUER=golem.network
      - MONGO_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/
      - HOST=0.0.0.0
      - PORT=5174
      - WS_PORT=5175
      - DB_NAME=depositDB
      - DEPOSIT_CONTRACT_ADDRESS=0x9CB8Ecc74e299eF9D3cBcf8f806F5C7b76CA08D3
      - YAGNA_SUBNET=payment_team_internal
    ports:
      - "5174:5174"
      - "5175:5175"
    depends_on:
      - yagna
      - mongo
    volumes:
      - ../:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: pnpm run start
    working_dir: /app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ../:/app
  # yagna service
  yagna:
    build:
      context: ./yagna
      dockerfile: Dockerfile
      args:
        - YAGNA_VERSION=pre-rel-v0.16.0-preview.deposit.13
    command: yagna service run
    ports:
      - "7465:7465"
    environment:
      - YAGNA_AUTOCONF_APPKEY=${YAGNA_APPKEY}
      - YAGNA_AUTOCONF_ID_SECRET=${YAGNA_PRIVATE_KEY}
      - YAGNA_API_URL=http://0.0.0.0:7465
      - GSB_URL=tcp://0.0.0.0:7464
      - YA_NET_BIND_URL=udp://0.0.0.0:0
      - YA_NET_RELAY_HOST=51.68.145.154:7464

  # mongo service
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=project
    ports:
      - "27017:27017"

  # mongo express service
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
      - mongo
    ports:
      - "8888:8081"
