name: Build docker files

on:
  push:

permissions:
  packages: write
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Create and push docker image
        run: |
          # login to ghcr.io
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          
          # build with full metadata
          docker build \
            --label "org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY}" \
            --label "org.opencontainers.image.description=Deposit payment example dockerized app" \
            --label "org.opencontainers.image.licenses=MIT" \
            -t ghcr.io/golemfactory/deposit_example:latest \
            --build-arg BACKEND_URL=http://deposit.dev.golem.network:5174 \
            .

          # push one image with two tags into repository
          docker push --all-tags ghcr.io/golemfactory/deposit_example

      - name: Notify Develop Server
        continue-on-error: true
        if: ${{ steps.get_image_tag.outputs.result == 'develop' }}
        run: curl http://deposit.dev.golem.network.:5000/release/pull
