#Location: .github/workflows/custom_config.yml

name: Build and push containers to Github Container Registry and apply rolling update
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: deposit-dev
    steps:
      - name: Where am I
        run: pwd

      - name: Who am I
        run: whoami

      - Name: checkout
        run: |
          cd /home/ubuntu/golem/deposit-payment-example
          git pull
          git submodule update --init --recursive

      - Name: install dependencies
        run: |
          cd /home/ubuntu/golem/deposit-payment-example
          pnpm install