#Location: .github/workflows/custom_config.yml

name: Build and push containers to Github Container Registry and apply rolling update
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: deposit-dev
    steps:
      - name: Where am I
        run: pwd

      - name: Who am I
        run: whoami

      - name: checkout
        run: |
          cd /home/ubuntu/golem/deposit-payment-example
          git pull
          git submodule update --recursive

      - name: install dependencies
        run: |
          cd /home/ubuntu/golem/deposit-payment-example
          /home/ubuntu/.nvm/versions/node/v21.7.3/bin/pnpm install

      - name: build
        run: |
          cd /home/ubuntu/golem/deposit-payment-example
          /home/ubuntu/.nvm/versions/node/v21.7.3/bin/pnpm run build:all